version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: kaojob
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/kaojob
      - JWT_SECRET=changeme123
      - PORT=3000
    depends_on:
      - db
    ports:
      - "3000:3000"
volumes:
  db-data:
